

const orderProp = ['deliver', 'has_coupon', 'is_open'];
const salseCenterFinal = [
        {
            "id": 355962,
            "title": "تهیه غذای امیر",
            "code": "444mox",
            "score": 0,
            "filtering": "irani",
            "highlight": "تهیه غذای امیر",
            "category": "",
            "rating": 0,
            "description": "ایرانی ,کباب",
            "commentCount": 61,
            "address": "بهجت آباد، خیابان شهید کلابی، کوچه شهید امیر هوشنگ قیومی ناصر، پلاک 43، تهیه غذای امیر",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/658d858a2633f.jpg",
            "has_coupon": true,
            "coupon_count": 3,
            "best_coupon": "چلو کباب کوبیده مرغ یک سیخ (160 گرم) رایگان با خرید حداقل 500 هزار تومان",
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": true,
            "discountValueForView": 30,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/uploads\/images\/vendor-cover-app-review\/2\/29.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendor-cover-app-review\/2\/29.jpg",
            "$id": "65cf1598cdf7df25ca47",
            "$createdAt": "2024-02-16T07:58:16.844+00:00",
            "$updatedAt": "2024-02-16T07:58:16.844+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 9345,
            "title": "پیتزا شیلا (مطهری)",
            "code": "31n4w0",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "پیتزا شیلا (مطهری)",
            "category": "",
            "rating": 9.2240082143191,
            "description": "سالاد و پیش‌غذا ,پیش غذا ,سالاد ,برگر ,پیش‌غذای ایرانی",
            "commentCount": 53385,
            "address": "خیابان ولیعصر، روبروی خیابان مطهری، برج بلوری، پیتزا شیلا (مطهری)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5e425b53b8b09.jpg",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/5e01b8ee2289b.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/5e01b8ee2289b.jpg",
            "$id": "65cf159bb7c8512ad8d3",
            "$createdAt": "2024-02-16T07:58:19.754+00:00",
            "$updatedAt": "2024-02-16T07:58:19.754+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 9346,
            "title": "پیتزا شیلا (میدان ولیعصر)",
            "code": "p5d5v0",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "پیتزا شیلا (میدان ولیعصر)",
            "category": "",
            "rating": 9.3000623304863,
            "description": "سالاد و پیش‌غذا ,پیش غذا ,سالاد ,برگر ,پیش‌غذای ایرانی",
            "commentCount": 59181,
            "address": "ضلع جنوب شرقی میدان ولیعصر، نبش کوچه شقایق، پلاک 46، پیتزا شیلا (میدان ولی عصر)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5e425b4fde54b.jpg",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/5e01b8e6e4ea5.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/5e01b8e6e4ea5.jpg",
            "$id": "65cf159ebe756075c160",
            "$createdAt": "2024-02-16T07:58:22.781+00:00",
            "$updatedAt": "2024-02-16T07:58:22.781+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 10791,
            "title": "کترینگ صدرسان (فاطمی)",
            "code": "0jxzq3",
            "score": 0,
            "filtering": "irani",
            "highlight": "کترینگ صدرسان (فاطمی)",
            "category": "",
            "rating": 8.8201910606974,
            "description": "ایرانی ,کباب ,سنتی",
            "commentCount": 54567,
            "address": "خیابان حجاب، روبه روی خانه والیبال، پلاک ۲۱، کترینگ صدرسان (فاطمی)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/659e59da89811.jpg",
            "has_coupon": true,
            "coupon_count": 2,
            "best_coupon": "سوپ رایگان با خرید خوراک جوجه کباب مخصوص",
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 15,
            "is_ecommerce": null,
            "is_eco": true,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/5bb9afb785e64.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/5bb9afb785e64.jpg",
            "$id": "65cf15a236c806f2be94",
            "$createdAt": "2024-02-16T07:58:26.226+00:00",
            "$updatedAt": "2024-02-16T07:58:26.226+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 31590,
            "title": "P.S (فیلیپر)",
            "code": "37x9q9",
            "score": 0,
            "filtering": "international",
            "highlight": "P.S (فیلیپر)",
            "category": "",
            "rating": 8.7173032999921,
            "description": "ایرانی ,کباب ,سنتی ,پیش‌غذای ایرانی",
            "commentCount": 63305,
            "address": "خیابان فاطمی٬ خیابان جویبار٬ پلاک٬28 P.S (فیلیپر)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5ee35a0c8e242.jpg",
            "has_coupon": true,
            "coupon_count": 2,
            "best_coupon": "ارسال رایگان و 5% تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 15,
            "is_ecommerce": null,
            "is_eco": true,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/6524fea882b63.jpeg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/6524fea882b63.jpeg",
            "$id": "65cf15a4f32755436a72",
            "$createdAt": "2024-02-16T07:58:28.997+00:00",
            "$updatedAt": "2024-02-16T07:58:28.997+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 235035,
            "title": "چیکن فامیلی (یوسف آباد)",
            "code": "0rgm5v",
            "score": 0,
            "filtering": "soxari",
            "highlight": "چیکن فامیلی (یوسف آباد)",
            "category": "",
            "rating": 8.7293371392325,
            "description": "سالاد و پیش‌غذا ,سالاد ,برگر ,پیش غذا ,سوخاری",
            "commentCount": 15585,
            "address": "یوسف آباد، نبش فتحی شقاقی، چیکن فامیلی (یوسف آباد)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/6231d0511986c.jpg",
            "has_coupon": true,
            "coupon_count": 1,
            "best_coupon": "ارسال رایگان و 5% تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/652517fa9fb82.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/652517fa9fb82.jpg",
            "$id": "65cf15a704c10f0afb4b",
            "$createdAt": "2024-02-16T07:58:31.020+00:00",
            "$updatedAt": "2024-02-16T07:58:31.020+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 254979,
            "title": "کترینگ صدرسان (یوسف آباد)",
            "code": "0mg42z",
            "score": 0,
            "filtering": "irani",
            "highlight": "کترینگ صدرسان (یوسف آباد)",
            "category": "",
            "rating": 8.9591677503251,
            "description": "ایرانی ,کباب ,چلو پلو ایرانی",
            "commentCount": 15200,
            "address": "یوسف آباد، نبش خیابان 11، پلاک 77، طبقه منفی یک، کترینگ صدرسان (یوسف آباد)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/659e59e2b3ccd.jpg",
            "has_coupon": true,
            "coupon_count": 2,
            "best_coupon": "سوپ جو رایگان با خرید چلو خورشت قیمه میکس",
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 15,
            "is_ecommerce": null,
            "is_eco": true,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/62cbd40116642.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/62cbd40116642.jpg",
            "$id": "65cf15a887cc05abe32e",
            "$createdAt": "2024-02-16T07:58:32.578+00:00",
            "$updatedAt": "2024-02-16T07:58:32.578+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 55898,
            "title": "چلوپز (فلسطین)",
            "code": "097446",
            "score": 0,
            "filtering": "irani",
            "highlight": "چلوپز (فلسطین)",
            "category": "",
            "rating": 8.6190103274436,
            "description": "ایرانی ,سنتی ,کباب ,چلو خورشت",
            "commentCount": 40682,
            "address": "میدان فاطمی، خیابان فلسطین، روبه روی کوچه رنجبر، پلاک 505، چلوپز (فلسطین)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5e9198c757160.jpg",
            "has_coupon": true,
            "coupon_count": 1,
            "best_coupon": "هدیه کاپوچینو بوکشتاین",
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": false,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/65250a934b411.jpeg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/65250a934b411.jpeg",
            "$id": "65cf15aa5e12bf0f4077",
            "$createdAt": "2024-02-16T07:58:34.386+00:00",
            "$updatedAt": "2024-02-16T07:58:34.386+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 9492,
            "title": "پیتزا شیلا (حجاب)",
            "code": "3kq2k3",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "پیتزا شیلا (حجاب)",
            "category": "",
            "rating": 9.3652373469031,
            "description": "سالاد و پیش‌غذا ,پیش غذا ,سالاد ,برگر ,پیش‌غذای ایرانی",
            "commentCount": 39909,
            "address": "خیابان فاطمی، خیابان حجاب، جنب سالن ورزشی حجاب، پلاک 7، پیتزا شیلا (حجاب)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/619b915865600.jpg",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/5e01b92bcbb88.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/5e01b92bcbb88.jpg",
            "$id": "65cf15aca720abc56f72",
            "$createdAt": "2024-02-16T07:58:36.685+00:00",
            "$updatedAt": "2024-02-16T07:58:36.685+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 344725,
            "title": "املت و دیزی سرای جمشید",
            "code": "gnlwdx",
            "score": 0,
            "filtering": "irani",
            "highlight": "املت و دیزی سرای جمشید",
            "category": "",
            "rating": 3.7777777777778,
            "description": "صبحانه ,سنتی ,دیزی",
            "commentCount": 9,
            "address": "کشاورز، خیابان شهید عباسقلی علیزاده (پنجم)، خیابان دکتر سید حسین فاطمی، پلاک 90، طبقه همکف، املت و دیزی سرای جمشید",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/6543fb02b5f9b.jpg",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/uploads\/images\/vendor-cover-app-review\/25\/02.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendor-cover-app-review\/25\/02.jpg",
            "$id": "65cf15ae89de4ae67520",
            "$createdAt": "2024-02-16T07:58:38.565+00:00",
            "$updatedAt": "2024-02-16T07:58:38.565+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 355127,
            "title": "کافه رستوران تن دی",
            "code": "dqq9kx",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "کافه رستوران تن دی",
            "category": "",
            "rating": 0,
            "description": "فست فود ,برگر",
            "commentCount": 0,
            "address": "خیابان زرتشت غربی، کوچه یزدان، پلاک 5، کافه رستوران تن دی",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/6589c53679bd8.png",
            "has_coupon": true,
            "coupon_count": 5,
            "best_coupon": "10٪ تخفیف با خرید حداقل 80 هزار تومان",
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/uploads\/images\/vendor-cover-app-review\/22\/01.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendor-cover-app-review\/22\/01.jpg",
            "$id": "65cf15b0a75178861efc",
            "$createdAt": "2024-02-16T07:58:40.707+00:00",
            "$updatedAt": "2024-02-16T07:58:40.707+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 45575,
            "title": "فست فود توتو (کریمخان)",
            "code": "3dg75x",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "فست فود توتو (کریمخان)",
            "category": "",
            "rating": 8.842688669417,
            "description": "سالاد و پیش‌غذا ,سس همراه غذا ,پیش غذا ,برگر ,سوخاری",
            "commentCount": 23817,
            "address": "میدان هفت‌تیر، خیابان کریمخان، پلاک 55، فست فود توتو (کریمخان)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5d413af42273c.jpg",
            "has_coupon": true,
            "coupon_count": 4,
            "best_coupon": "ارسال رایگان و 5% تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 30,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/5d8f2ff939ec5.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/5d8f2ff939ec5.jpg",
            "$id": "65cf15b9db1b401ff787",
            "$createdAt": "2024-02-16T07:58:49.933+00:00",
            "$updatedAt": "2024-02-16T07:58:49.933+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 68737,
            "title": "رستوران روحی (کریم خان)",
            "code": "p87ke5",
            "score": 0,
            "filtering": "irani",
            "highlight": "رستوران روحی (کریم خان)",
            "category": "",
            "rating": 8.8545427196149,
            "description": "ایرانی ,سنتی ,کباب ,صبحانه ,چلو پلو ایرانی ,چلو خورشت",
            "commentCount": 13116,
            "address": "خیابان کریم خان زند، بین خیابان ایرانشهر و ماهشهر، جنب انتشارات ثالث، رستوران روحی (کریم خان)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/604777aceaed3.jpg",
            "has_coupon": true,
            "coupon_count": 3,
            "best_coupon": "ارسال رایگان و 5% تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/65250e98e4ae9.jpeg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/65250e98e4ae9.jpeg",
            "$id": "65cf15c7da519216fac0",
            "$createdAt": "2024-02-16T07:59:03.895+00:00",
            "$updatedAt": "2024-02-16T07:59:03.895+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 271125,
            "title": "گریل گایز (فلسطین)",
            "code": "0g71vq",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "گریل گایز (فلسطین)",
            "category": "",
            "rating": 8.9513203214696,
            "description": "فست فود ,برگر ,صبحانه ,سالاد ,سوخاری",
            "commentCount": 8530,
            "address": "میدان فاطمی، خیابان فلسطین، روبه روی کوچه رنجبر، پلاک 505، گریل گایز (فلسطین)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/6339407ebf488.jpg",
            "has_coupon": true,
            "coupon_count": 3,
            "best_coupon": "5٪ تخفیف با خرید از دسته‌ی کمبو",
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 30,
            "is_ecommerce": false,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/644b7a88124ff.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/644b7a88124ff.jpg",
            "$id": "65cf15cc52ba7a9bd068",
            "$createdAt": "2024-02-16T07:59:08.340+00:00",
            "$updatedAt": "2024-02-16T07:59:08.340+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 78721,
            "title": "کترینگ سینتو پلو",
            "code": "314nn2",
            "score": 0,
            "filtering": "irani",
            "highlight": "کترینگ سینتو پلو",
            "category": "",
            "rating": 8.6782871696912,
            "description": "ایرانی ,کباب ,چلو خورشت  ,سنتی ,مرغ",
            "commentCount": 12384,
            "address": "میدان ولی عصر، خیابان شقایق، کوچه 3، پلاک 5، کترینگ سینتو پلو",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/65a548a44963d.jpg",
            "has_coupon": true,
            "coupon_count": 2,
            "best_coupon": "ارسال رایگان و 5٪ تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": null,
            "is_eco": true,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/cdn\/vendor_sub_types\/3\/16.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/cdn\/vendor_sub_types\/3\/16.jpg",
            "$id": "65cf15d0ab46c04ec226",
            "$createdAt": "2024-02-16T07:59:12.702+00:00",
            "$updatedAt": "2024-02-16T07:59:12.702+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 360659,
            "title": "آشکده چوبین (فلسطین)",
            "code": "r5jjv8",
            "score": 0,
            "filtering": "irani",
            "highlight": "آشکده چوبین (فلسطین)",
            "category": "",
            "rating": 0,
            "description": "",
            "commentCount": 25,
            "address": "میدان فاطمی، خیابان فلسطین، روبه روی کوچه رنجبر، پلاک 505، آشکده (فلسطین)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/www.zoodfood.com",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": false,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/cdn\/vendor_sub_types\/32\/04.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/cdn\/vendor_sub_types\/32\/04.jpg",
            "$id": "65cf15d497d808008b73",
            "$createdAt": "2024-02-16T07:59:16.623+00:00",
            "$updatedAt": "2024-02-16T07:59:16.623+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 84060,
            "title": "ته چین بار (مطهری)",
            "code": "poy9lk",
            "score": 0,
            "filtering": "irani",
            "highlight": "ته چین بار (مطهری)",
            "category": "",
            "rating": 8.7362032691374,
            "description": "ایرانی ,سنتی ,پیش‌غذای ایرانی ,نوشیدنی سرد و بستنی",
            "commentCount": 12178,
            "address": "خیابان ولیعصر، ابتدای خیابان مطهری، بعد از کوچه سربداران، جنب فروشگاه شیرین عسل، پلاک 472، طبقه 1، ته چین بار (مطهری)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/6110ee0098a41.jpg",
            "has_coupon": true,
            "coupon_count": 3,
            "best_coupon": "ارسال رایگان و تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": null,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/652670cd10c74.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/652670cd10c74.jpg",
            "$id": "65cf15da509c53861fc1",
            "$createdAt": "2024-02-16T07:59:22.331+00:00",
            "$updatedAt": "2024-02-16T07:59:22.331+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 28009,
            "title": "رستوران عمارت لاله",
            "code": "0q6ogy",
            "score": 0,
            "filtering": "irani",
            "highlight": "رستوران عمارت لاله",
            "category": "",
            "rating": 8.6101023890785,
            "description": "ایرانی ,کباب",
            "commentCount": 14470,
            "address": "خیابان کارگر شمالی، بالاتر از بلوار کشاورز، نبش کوچه ارجمند ، پلاک 1، رستوران عمارت لاله",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5b62e74fe412e.jpg",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/uploads\/images\/vendor-cover-app-review\/28\/05.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendor-cover-app-review\/28\/05.jpg",
            "$id": "65cf15e063d5186f9ec8",
            "$createdAt": "2024-02-16T07:59:28.410+00:00",
            "$updatedAt": "2024-02-16T07:59:28.410+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 63279,
            "title": "عطاویچ (بلوار کشاورز)",
            "code": "0m1xdo",
            "score": 0,
            "filtering": "irani",
            "highlight": "عطاویچ (بلوار کشاورز)",
            "category": "",
            "rating": 8.5218650007618,
            "description": "صبحانه و میان‌وعده ,صبحانه ,پیش غذا ,سوخاری",
            "commentCount": 12946,
            "address": "خیابان فلسطین، نرسیده بلوار کشاورز، پلاک 436، عطاویچ (بلوار کشاورز)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/63c28d340b6fc.jpg",
            "has_coupon": true,
            "coupon_count": 5,
            "best_coupon": "ارسال رایگان و 5% تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 20,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/63a15e5014c66.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/63a15e5014c66.jpg",
            "$id": "65cf15e7ed5dd68d682a",
            "$createdAt": "2024-02-16T07:59:35.973+00:00",
            "$updatedAt": "2024-02-16T07:59:35.973+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 61926,
            "title": "هایدا (میدان ولیعصر)",
            "code": "097g8y",
            "score": 0,
            "filtering": "fastFood",
            "highlight": "هایدا (میدان ولیعصر)",
            "category": "",
            "rating": 7.820763956905,
            "description": "سالاد و پیش‌غذا ,سالاد ,برگر ,پیش غذا",
            "commentCount": 7988,
            "address": "میدان ولیعصر، ابتدای بلوار کشاورز، پلاک 12، هایدا (میدان ولیعصر)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/5f95fed27e123.jpg",
            "has_coupon": false,
            "coupon_count": null,
            "best_coupon": null,
            "is_pro": false,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/602e422c22966.jpg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/602e422c22966.jpg",
            "$id": "65cf15f162880f18aa83",
            "$createdAt": "2024-02-16T07:59:45.425+00:00",
            "$updatedAt": "2024-02-16T07:59:45.425+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        },
        {
            "id": 82153,
            "title": "باماهاس (یوسف آباد)",
            "code": "pv1n2x",
            "score": 0,
            "filtering": "irani",
            "highlight": "باماهاس (یوسف آباد)",
            "category": "",
            "rating": 8.9715129774214,
            "description": "سالاد و پیش‌غذا ,پیش‌غذای ایرانی ,سالاد",
            "commentCount": 9298,
            "address": "یوسف آباد، فتحی شقاقی، خیابان جهانمهر، نبش کوچه 6.1، پلاک 36، باماهاس (یوسف آباد)",
            "is_open": true,
            "is_preorder_enabled": false,
            "is_express": true,
            "featured": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_logo\/uploads\/images\/vendors\/logos\/615d9f0bebfd5.jpg",
            "has_coupon": true,
            "coupon_count": 5,
            "best_coupon": "ارسال رایگان و 10% تخفیف ویژه کاربران PRO",
            "is_pro": true,
            "deliver": true,
            "is_pickup": false,
            "bid": false,
            "discountValueForView": 0,
            "is_ecommerce": null,
            "is_eco": false,
            "delivery_fee": -1,
            "backgroundImage": "https:\/\/cdn.snappfood.ir\/media\/cache\/vendor_item_cover\/uploads\/images\/vendors\/covers\/62cbec4482ba7.jpeg",
            "backgroundImageCustom": "https:\/\/cdn.snappfood.ir\/w.x.h\/uploads\/images\/vendors\/covers\/62cbec4482ba7.jpeg",
            "$id": "65cf15f6426ed1712fee",
            "$createdAt": "2024-02-16T07:59:50.273+00:00",
            "$updatedAt": "2024-02-16T07:59:50.273+00:00",
            "$permissions": [],
            "$databaseId": "659a6a22e9ce96f0193c",
            "$collectionId": "65ce89cbec324aa9b923"
        }
    ]

const abab = salseCenterFinal.filter(item => {
        
    for (let propItem of orderProp){
        if(propItem === "deliver" && item.deliver !== true){
            return false;
        }
        if(propItem === "has_coupon" && item.has_coupon !== true){
            return false;
        }
        if(propItem === "is_open" &&  item.is_open !== true){
            return false;
        }
        if(propItem === "is_express" && item.is_express !== true ){
            return false;
        }
        if(propItem === "is_eco" && item.is_eco !== true ){
            return false;
        }
        return
    }
});